# Dockerfile.web
FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /usr/src/app


RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]


# 컨테이너 실행 명령 (Gunicorn을 Django의 WSGI 엔트리포인트에 바인딩)
CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]